server:
  port: ${PORT}
  servlet.context-path: /api
spring:
  application.name: person-rest
  # DB properties
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate.ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
# OpenAPI
springdoc:
  api-docs.path: /docs
  swagger-ui.path: /docs-ui
