version: "3"
services:
  postgres:
    image: postgres:10-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: persons
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  persons:
    build:
      context: ./people-rest
      dockerfile: Dockerfile
    restart: "no"
    environment:
      DATABASE_URL: postgresql://postgres:5432/persons
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      PORT: 8888
    ports:
      - "8888:8888"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: curl -sS http://localhost:8888/actuator/health || echo 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      persons:
        condition: service_healthy
    healthcheck:
      test: service nginx status || echo 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
